# Generated by Django 2.1.8 on 2019-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
