# Generated by Django 2.1.8 on 2019-05-04 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_polls_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='video_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polls',
            name='video_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
