# Generated by Django 2.1.8 on 2019-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190504_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='like',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
