# Generated by Django 2.1.8 on 2019-05-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_polls_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='like',
        ),
    ]
